### ISSUE TITLE
Use Jens Segers' Date instead of Carbon

### ISSUE THREAD

**Issue by Evertt** [TheDevNetwork/PhpTypes#20]
It does everything Carbon does (since it extends it), but it adds multi-language support to it.

https://github.com/jenssegers/date

**Comment by vpassapera** [comment]
Will do it on the next update! Thanks!

**Comment by vpassapera** [comment]
I'm updating this for php8 and it looks like carbon has localization support now. But the jenssegers/date looks like it's more tailed to Laravel Developers, and uses facade pattern which I am not a fan of.
